///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Increase Bard Song to 1 Turn                                          //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Add Required Files to Override                                        //
///////////////////////////////////////////////////////////////////////////
COPY ~skills-and-abilities/spl/class/MOBAR01.SPL~ ~override~ // Bard Song Duration Increase

///////////////////////////////////////////////////////////////////////////
// Modify Base Bard CLAB File                                            //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~CLABBA01.2DA~ override
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_MOBAR01 END
    PRETTY_PRINT_2DA
  BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Set Skills for ALL Bard Kits                                          //
///////////////////////////////////////////////////////////////////////////
 COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~bard_kitlist~ 10
  FOR (row = 3; row < bard_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~bard_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~bard_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~bard_kitlist~ row 8 kit_class
  
  PATCH_IF (%kit_class% = 5) BEGIN
    // Modify Bard CLAB File to Assign Thief Skills Points Every Level
    // Remove once EEex is updated for Bard Thief Skill Natural Progression
    // delete lib.2da too when this gets removed
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      // Update Bard Song Duration
      COPY_EXISTING ~%kit_clab%.2DA~ override
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_MOBAR01 END
          PRETTY_PRINT_2DA
        BUT_ONLY
      END
    END
  END
  END
