///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Allow Inquisitor to Cast Divine Spells                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Modify Base Inquisitor CLAB File                                      //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~CLABPA03.2DA~ override
  REPLACE_TEXTUALLY ~AP_SPCL234~ ~****~ // Remove True Seeing
  PRETTY_PRINT_2DA
BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Modify kitlist.2da and Clabpa.2da for Inquisitor                      //
///////////////////////////////////////////////////////////////////////////
 COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~pal_kitlist~ 10
  FOR (row = 3; row < pal_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~pal_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~pal_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~pal_kitlist~ row 8 kit_class
  REPLACE_TEXTUALLY ~0x00000010~ ~0x00004000~
  
  PATCH_IF NOT ~%kit_class%~ STRING_EQUAL_CASE ~*~ BEGIN
    PATCH_IF (%kit_class% = 6) BEGIN
      // Set New Paladin Abilities
      PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
        INNER_ACTION BEGIN
        // Add new abilities to all Paladin kits
        COPY_EXISTING ~%kit_clab%.2DA~ override
        PATCH_IF ("%kit_label%" STRING_EQUAL_CASE "INQUISITOR") BEGIN
          REPLACE_TEXTUALLY ~AP_SPCL234~ ~****~
          PRETTY_PRINT_2DA
        END
        BUT_ONLY
        END
      END
    END
  END
  END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Updates descriptions for Inquisitor                                   //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
OUTER_SPRINT old_inq @6011 //old text

OUTER_SPRINT new_inq @6012 //new text

// Set the strref for the specific game first
ACTION_IF GAME_IS ~bgee~ BEGIN
  OUTER_SET inq1_strref = 24288 // BGEE strref
END ELSE ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
  OUTER_SET inq1_strref = 25207 // BG2EE and EET strref
END ELSE ACTION_IF GAME_IS ~iwdee~ BEGIN
  OUTER_SET inq1_strref = 37137 // IWDEE strref
END

ACTION_GET_STRREF ~%inq1_strref%~ inq1_description

OUTER_PATCH_SAVE inq1_description ~%inq1_description%~ BEGIN
  REPLACE_TEXTUALLY ~%old_inq%~ ~%new_inq%~
END

STRING_SET_EVALUATE ~%inq1_strref%~ ~%inq1_description%~