///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Update Paladin Class and Kits                                         //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Import                                                                //
///////////////////////////////////////////////////////////////////////////
COPY ~skills-and-abilities/eff/class/MO#PHL01.EFF~ ~override~ // Sanctify Strikes
COPY ~skills-and-abilities/spl/MOPHL01.SPL~        ~override~ // Sanctify Strikes
COPY ~skills-and-abilities/spl/MO#PHL01.SPL~       ~override~ // Sanctify Strikes
  SAY NAME1 @6003
  SAY UNIDENTIFIED_DESC @6004

///////////////////////////////////////////////////////////////////////////
// Set Base Paladin New Abilities                                        //
///////////////////////////////////////////////////////////////////////////
/*
COPY_EXISTING ~CLABPA01.2DA~ override
    LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_MO#MON02 END
    PRETTY_PRINT_2DA
  BUT_ONLY
  */

///////////////////////////////////////////////////////////////////////////
// Add HLAs                                                              //
///////////////////////////////////////////////////////////////////////////
LAF ADD_HLA INT_VAR class = 6 min_lev = 1 max_lev = 99 num_allowed = 1 STR_VAR ability = AP_MO#PHL01 END  

///////////////////////////////////////////////////////////////////////////
// Set Abilities for all Paladin Kits                                    //
///////////////////////////////////////////////////////////////////////////
 /*
 COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~pal_kitlist~ 10
  FOR (row = 3; row < pal_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~pal_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~pal_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~pal_kitlist~ row 8 kit_class
  
  PATCH_IF (%kit_class% = 6) BEGIN
    // Set New Paladin Abilities
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      // Add new abilities to all Paladin kits
      COPY_EXISTING ~%kit_clab%.2DA~ override
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_MO#MON02 END
        //LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 f_MaxLevel = 15 f_Increment = 1 STR_VAR f_Entry = AP_MO#MON01 END
        PRETTY_PRINT_2DA
      BUT_ONLY
      END
    END
  END
  END
*/
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Updates descriptions for Paladin                                      //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
