///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Overhaul Turn Undead                                                  //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Add Required Files to Override                                        //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~M_B3THI7.lua~ THEN BEGIN
  COPY ~skills-and-abilities/lua/M_B3TUR1.lua~ ~override~ // Inquisitor Dispel Illusion
END ELSE BEGIN
  COPY ~skills-and-abilities/lua/M_B3TUR2.lua~ ~override~ // NO Inquisitor Dispel Illusion
END

COPY ~skills-and-abilities/lua/M_B3TUR3.lua~   ~override~ // Cleric, Fighter/Cleric, Cleric/Mage, FMC 
COPY ~skills-and-abilities/lua/M_B3TUR4.lua~   ~override~ // Cleric/Thief 
COPY ~skills-and-abilities/lua/M_B3TUR5.lua~   ~override~ // Cleric/Ranger

FOR (i = 1; i < 10; ++i) BEGIN
  INNER_ACTION BEGIN
    COPY ~skills-and-abilities/eff/class/motur01.eff~ ~override/motur0%i%.eff~
      WRITE_LONG 0x1c i
  END
END

FOR (j = 10; j < 51; ++j) BEGIN
  INNER_ACTION BEGIN
    COPY ~skills-and-abilities/eff/class/motur01.eff~ ~override/motur%j%.eff~
      WRITE_LONG 0x1c j
  END
END

COPY ~skills-and-abilities/spl/MOTURN1.SPL~    ~override~ // Turn Undead
  SAY NAME1 @9001
  SAY UNIDENTIFIED_DESC @9002

///////////////////////////////////////////////////////////////////////////
// Give Paladin Turn Undead Ability                                      //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~CLABPA01.2DA~ override
    LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 4 STR_VAR f_Entry = GA_MOTURN1 END 
    PRETTY_PRINT_2DA
  BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Give Cleric Turn Undead Ability                                       //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~CLABPR01.2DA~ override
    LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 f_Increment = 3 STR_VAR f_Entry = GA_MOTURN1 END 
    PRETTY_PRINT_2DA
  BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Give Cleric and Paladin Kits Turn Undead Ability                      //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~kitlist~ 10
  FOR (row = 3; row < kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~kitlist~ row 8 kit_class
  PATCH_IF (%kit_class% = 6) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ AND !("%kit_label%" STRING_EQUAL_CASE "INQUISITOR") BEGIN
      INNER_ACTION BEGIN
        COPY_EXISTING ~%kit_clab%.2DA~ override
          LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 4 STR_VAR f_Entry = GA_MOTURN1 END
          PRETTY_PRINT_2DA
        BUT_ONLY
      END
    END
  END ELSE PATCH_IF (%kit_class% = 3) BEGIN
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
        COPY_EXISTING ~%kit_clab%.2DA~ override
          LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 f_Increment = 3 STR_VAR f_Entry = GA_MOTURN1 END
          PRETTY_PRINT_2DA
        BUT_ONLY
      END
    END
  END
  END